name: docker_deploy

on:
  workflow_dispatch:
#  push:
#    branches:
#      - 'main'

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Add parsing of R DESCRIPTION version here to create version-tag?
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: | 
           tanho63/dpcalc:latest
